### PR TITLE
Add newer images here.

### PR DESCRIPTION
**Pull request by jbelmont**
@xdumaine I just basically copied all the images from web-directory/public/assets/images/ico because I saw  a bunch of them now and don't know which ones we should use

### CODE REVIEW

**Comment by jbelmont** [comment]
Also I remember running the rake task but forgot what you did to upload them again

**Comment by xdumaine** [comment]
@jbelmont can you just replace the ones that are in here now, instead of adding new files?

**Comment by jbelmont** [comment]
@xdumaine yeah I just don't know which ones to replace them with:

icon-128.png
icon-16.png
icon-48.png

I don't see these exact dimensions in web-directory

**Comment by jbelmont** [comment]
@xdumaine Okay I updated to newer png.s using the tool I am going to mark the steps I did for my future reference so ignore what I am write here

```bash
$ cd ~/genesys/web-directory/public/assets/images/svg
$ svgexport genesys-logo-red.svg icon-48.png 48:
$ svgexport genesys-logo-red.svg icon-128.png 128:
$ svgexport genesys-logo-red.svg icon-16.png 16:
$ mv *.png ../../../../../chrome-screenshare-extension/extension/images/
```

**Comment by jbelmont** [comment]
Nothing else you want me to do for chrome-screenshare-extension, correct?

**Pull request merged**
